# Generated by Django 4.0.4 on 2022-06-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit_Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_rate',
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
