# Generated by Django 4.0.3 on 2022-10-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('UGX', 'UGX'), ('USD', 'USD'), ('GBP', 'GBP')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_excise_duty',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.CharField(choices=[('18%', 'Standard Rated Sale'), ('-', 'Export'), ('0%', 'Exempt')], default='18%', max_length=30),
        ),
    ]
