# Generated by Django 4.0.4 on 2022-06-01 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_unit_measurement_remove_product_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.unit_measurement'),
        ),
    ]
