# Generated by Django 4.0.3 on 2022-11-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_product_currency_alter_product_has_excise_duty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='c_code',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Client Code'),
        ),
    ]
