# Generated by Django 4.0.5 on 2022-06-17 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_productmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmeta',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.company'),
        ),
    ]
