# Generated by Django 4.0.4 on 2022-06-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_product_unit_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.CharField(choices=[('18%', '18%'), ('0%', '0%')], default='18%', max_length=3),
        ),
    ]
