# Generated by Django 4.0.5 on 2022-06-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_productmeta_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproducts',
            name='vat',
            field=models.CharField(choices=[('18%', 'Standard Rated Sale'), ('0%', 'Export'), ('0%', 'Exempt')], max_length=100, null=True, verbose_name='VAT'),
        ),
    ]
