# Generated by Django 4.0.4 on 2022-06-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_product_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='piece_measure_unit',
        ),
        migrations.AlterField(
            model_name='company',
            name='companyLogo',
            field=models.ImageField(blank=True, default='default_logo.jpg', null=True, upload_to='company_logos'),
        ),
    ]
