# Generated by Django 4.0.4 on 2022-06-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_remove_product_piece_measure_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_measurement',
            name='code',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
