# Generated by Django 4.0.4 on 2022-06-01 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_unit_measurement_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceproducts',
            name='client',
        ),
        migrations.AddField(
            model_name='invoiceproducts',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoice'),
        ),
    ]
