# Generated by Django 4.0.5 on 2022-06-23 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_bankdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_details', to='invoice.company'),
        ),
        migrations.CreateModel(
            name='CompanyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot', models.CharField(max_length=1000, null=True)),
                ('pobox', models.CharField(max_length=1000, null=True, verbose_name='P.O.Box')),
                ('location', models.CharField(default='Kampala, Uganda', max_length=1000, null=True)),
                ('other_details', models.CharField(max_length=1000, null=True)),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.company')),
            ],
        ),
    ]
