# Generated by Django 4.0.4 on 2022-06-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_remove_invoiceproducts_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, choices=[('UGX', 'UGX'), ('USD', 'USD'), ('GBP', 'GBP')], max_length=100, null=True, verbose_name='CURRENCY'),
        ),
        migrations.AlterField(
            model_name='invoiceproducts',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Unit Price'),
        ),
    ]
