# Generated by Django 4.0.4 on 2022-06-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_company_email_alter_invoice_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproducts',
            name='price',
            field=models.FloatField(verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='invoiceproducts',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
