# Generated by Django 4.0.5 on 2022-06-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_alter_bankdetails_company_companylocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='short_name',
            field=models.CharField(default='BDO', max_length=10),
            preserve_default=False,
        ),
    ]
