# Generated by Django 4.0.5 on 2022-06-23 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_company_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.company'),
        ),
        migrations.AlterField(
            model_name='invoiceproducts',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv_prod', to='invoice.invoice'),
        ),
    ]
