# Generated by Django 4.0.5 on 2022-06-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_invoice_company_alter_invoiceproducts_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Company',
            new_name='company',
        ),
    ]
