# Generated by Django 4.0.5 on 2022-06-10 15:41

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_invoiceproducts_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='qrcode',
        ),
        migrations.AddField(
            model_name='invoice',
            name='json_response',
            field=jsonfield.fields.JSONField(default=1991),
            preserve_default=False,
        ),
    ]
