# Generated by Django 4.0.5 on 2022-06-15 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_alter_invoice_json_response_creditnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='json_response',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='invoice.invoice'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
