# Generated by Django 4.0.5 on 2022-06-29 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_alter_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.company'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='reason_code',
            field=models.CharField(choices=[('101', 'Return of products due to expiry or damage, etc.'), ('102', 'Cancellation of the purchase'), ('103', 'Invoice amount wrongly stated due to miscalculation of price, tax or discounts, etc.'), ('104', 'Partial or complete waive off of the service sale after the invoice is generated and sent to the customer'), ('105', 'Others (Please specify')], max_length=100000000),
        ),
    ]
