# Generated by Django 4.0.5 on 2022-06-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_creditnote_json_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='reference',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
