# Generated by Django 4.0.5 on 2022-07-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_client_type_alter_company_company_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='nin_brn',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_type',
        ),
        migrations.AddField(
            model_name='client',
            name='company_type',
            field=models.CharField(choices=[('B2B', 'Business'), ('B2G', 'Government'), ('B2C', 'Consumer'), ('B2F', 'Foreigner')], max_length=100, null=True),
        ),
    ]
