# Generated by Django 4.0.5 on 2022-06-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_creditnote_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
