# Generated by Django 4.0.5 on 2022-07-01 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_remove_client_nin_brn_remove_company_company_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='type',
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_type',
            field=models.CharField(choices=[('0', 'Business'), ('3', 'Government'), ('1', 'Consumer'), ('2', 'Foreigner')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='tin',
            field=models.CharField(blank=True, help_text='leave blank if export', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='CnCancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('101', 'Buyer refused to accept the invoice due to incorrect invoice/receipt'), ('102', 'Not delivered due to incorrect invoice/receipt'), ('103', 'Other reasons')], max_length=10000, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('cn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.creditnote')),
            ],
        ),
    ]
