# Generated by Django 4.0.5 on 2022-07-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_remove_client_type_alter_client_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterField(
            model_name='invoiceproducts',
            name='vat',
            field=models.CharField(choices=[('18%', 'Standard Rated Sale'), ('-', 'Export'), ('0%', 'Exempt')], max_length=100, null=True, verbose_name='VAT'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.CharField(choices=[('18%', 'Standard Rated Sale'), ('-', 'Export'), ('0%', 'Exempt')], default='18%', max_length=3),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_type',
            field=models.ManyToManyField(to='invoice.tax_type'),
        ),
    ]
