# Generated by Django 4.0.5 on 2022-07-06 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_remove_client_tax_type_client_tax_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproducts',
            name='tax_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoice.tax_type'),
            preserve_default=False,
        ),
    ]
