# Generated by Django 4.0.5 on 2022-07-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0019_invoiceproducts_tax_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tax_type',
        ),
    ]
