# Generated by Django 4.0.5 on 2022-07-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_remove_client_tax_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cncancel',
            name='details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
