# Generated by Django 4.0.5 on 2022-07-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0021_cncancel_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cncancel',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='creditnote',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='invoiceproducts',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='productmeta',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='productmeta',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
