# Generated by Django 4.0.5 on 2022-07-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0022_alter_cncancel_options_alter_creditnote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='nature',
            field=models.CharField(default='1', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='vat_wht',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='remarks',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
