# Generated by Django 4.0.5 on 2022-07-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_company_nature_company_vat_wht_alter_invoice_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='comp_url',
            field=models.URLField(null=True),
        ),
    ]
