# Generated by Django 4.0.5 on 2022-07-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0025_rename_comp_url_company_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='approval',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='fdn',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
