# Generated by Django 4.0.5 on 2022-07-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0026_creditnote_approval_creditnote_fdn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyLogo',
            field=models.ImageField(blank=True, default='default_logo.jpg', null=True, upload_to='company_logos', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, help_text='Separate Each location Detail with >', max_length=1000),
        ),
        migrations.AlterField(
            model_name='company',
            name='nature',
            field=models.CharField(choices=[('Services', 'Services'), ('Products', 'Products')], max_length=120),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='approval',
            field=models.CharField(default='Pending', max_length=122, null=True),
        ),
    ]
