# Generated by Django 4.0.5 on 2022-08-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0027_alter_company_companylogo_alter_company_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='anti_fake',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyLogo',
            field=models.ImageField(default='default_logo.jpg', null=True, upload_to='company_logos', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(help_text='Separate Each location Detail with >', max_length=1000),
        ),
        migrations.AlterField(
            model_name='company',
            name='telephone_number',
            field=models.CharField(max_length=100),
        ),
    ]
