# Generated by Django 4.0.5 on 2022-08-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0028_creditnote_anti_fake_alter_company_companylogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
