# Generated by Django 4.0.5 on 2022-08-29 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0030_barcode_alter_company_device_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='business_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('UGX', 'UGX'), ('USD', 'USD'), ('GBP', 'GBP')], max_length=100, null=True, verbose_name='CURRENCY'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('107', 'EFT'), ('106', 'Visa'), ('105', 'Mobile money'), ('103', 'Cheque'), ('102', 'Cash'), ('101', 'Credit')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='remarks',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceproducts',
            name='tax_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.tax_type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(help_text='The code should be unique to all produucts', max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='commodity_id',
            field=models.CharField(help_text='An 18 digit code from URA coding system', max_length=18),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_excise_duty',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(default=1, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='productmeta',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productmeta',
            name='stock',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
