# Generated by Django 4.1.1 on 2022-09-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0031_alter_client_business_name_alter_invoice_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(help_text='The code should be unique to all produucts', max_length=40),
        ),
    ]
