# Generated by Django 4.0.3 on 2022-09-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0032_alter_client_email_address_alter_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
